icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#93a1a1"
idle_fg = "#ffffff"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "battery"
interval = 10
show = "percentage"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
